#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPT_DIR/helper.sh

path="$(fullpath "$1")"
if [[ -f "$path" ]]; then
    $SCRIPT_DIR/run -p to_json.py -f "$path" -- --show --dry-run
else
    #crawling sstill not implemented
    $SCRIPT_DIR/run -p to_json.py -D "$path" -- --show --dry-run
fi
