#!/bin/bash

path="$1"
file="$(basename "$path")"
basedir="$( cd "$(dirname "$path")"; pwd)"

#TODO user run.sh
docker run --rm -v "$basedir:/data" -e "DATA_PATH=$basedir" publisher /scripts/to_json.py --show "/data/$file"

